name: Daily Update

on:
  schedule:
    - cron: "0 5 * * *" # Runs daily at midnight COT
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  daily-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # Save TOKEN secret into token.json
      - name: Save TOKEN secret
        run: echo "${{ secrets.TOKEN }}" > token.json
      # Build and run Dockerfile with .env.colombia environment file
      - name: Build and run Docker container
        run: |
          docker build -t daily-update .
          docker run --env-file .env.colombia daily-update
